name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    # Prevents running multiple release scripts at the same time
    concurrency: 'release'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN  || secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN  || secrets.PAT }}
        run: npx semantic-release
